version: '3'
services:
  backend:
    container_name: webAPI
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - uploads:/uploads
      - dtr:/backend/dtr
      - office-invoice:/backend/office/invoice
      - tech-inventory:/backend/technical/inventory
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: UI
    build:
      context: ./frontend-ts
      dockerfile: Dockerfile
    volumes:
      - static-v2:/usr/share/nginx/html
    ports:
      - "8080:8080"

    
  db:
    container_name: Database
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YE$
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  nginx:
    image: "nginx"
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
      - static-v2:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
volumes:
  static-v2:
    driver: local
  db-data:
  uploads:
  dtr:
  office-invoice:
  tech-inventory: