version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend-ts
      dockerfile: Dockerfile
    volumes:
      - static-volume:/usr/share/nginx/html
    ports:
      - "8080:8080"

    

  db:
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YE$
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  nginx:
    image: "nginx"
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
      - static-volume:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
volumes:
  static-volume: