version: '3'
services:
  backend:
    container_name: webAPI
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - uploads:/uploads
      - dtr:/backend/dtr
      - office-invoice:/backend/office/invoice
      - tech-inventory:/backend/technical/inventory
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db
    command: daphne -e ssl:8443:privateKey=server.key:certKey=server.crt backend.asgi:application
    ports:
      - "8443:8443"

  frontend:
    container_name: UI
    build:
      context: ./frontend-ts
      dockerfile: Dockerfile
    volumes:
      - static-v7:/usr/share/nginx/html
    ports:
      - "8080:8080"

    
  db:
    container_name: Database
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YE$
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  frontend-proxy:
    image: "nginx"
    volumes:
      - ./frontend-nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
      - static-v7:/usr/share/nginx/html
      - ./ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

volumes:
  static-v7:
    driver: local
  db-data:
  uploads:
  dtr:
  office-invoice:
  tech-inventory: