# Generated by Django 4.0.6 on 2022-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TXLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('line_voltage', models.FloatField()),
                ('exciter', models.FloatField()),
                ('driver_current', models.FloatField()),
                ('driver_forward', models.FloatField()),
                ('driver_rf', models.FloatField()),
                ('tx_current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('tx_forward', models.FloatField()),
                ('tx_rf', models.FloatField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
