# Generated by Django 4.0.6 on 2022-12-11 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transmitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='txlog',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txlog',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='txlog',
            name='timeround',
            field=models.IntegerField(null=True),
        ),
    ]
