# Generated by Django 4.0.6 on 2022-12-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitter', '0003_rename_timeround_txlog_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txlog',
            old_name='tx_current',
            new_name='driver_voltage',
        ),
        migrations.RenameField(
            model_name='txlog',
            old_name='tx_forward',
            new_name='final_current',
        ),
        migrations.RenameField(
            model_name='txlog',
            old_name='tx_rf',
            new_name='final_forward',
        ),
        migrations.RenameField(
            model_name='txlog',
            old_name='voltage',
            new_name='final_rf',
        ),
        migrations.AddField(
            model_name='txlog',
            name='final_voltage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
